import assert from "node:assert/strict";
import test from "node:test";
import { ADDITION_VIEWS, additionViewModel, createAdditionState, finishAdditionMovement, moveAdditionSummand, nextAdditionState, resetAdditionState } from "../src/addition-negative-state.js";

test("Aufbau trennt Irritation, Start, Rechenzeichen, Vorzeichen, Bewegung und Ergebnis",()=>{let s=createAdditionState();assert.equal(s.view,"prompt");for(const view of ["start","operator","summand"]){s=nextAdditionState(s);assert.equal(s.view,view);assert.equal(s.locked,false);}s=nextAdditionState(s);assert.equal(s.view,"moving");assert.equal(s.locked,true);assert.strictEqual(nextAdditionState(s),s);s=finishAdditionMovement(s);assert.equal(s.view,"result");assert.equal(s.locked,false);s=nextAdditionState(s);assert.equal(s.view,"free");});
test("Ansichtsmodell zeigt nichts mathematisch verfrüht",()=>{const prompt=additionViewModel(createAdditionState());assert.equal(prompt.showAxis,false);assert.equal(prompt.showFormula,false);assert.equal(prompt.showMotion,false);const start=additionViewModel({view:ADDITION_VIEWS.start,summand:-5,locked:false});assert.equal(start.showAxis,true);assert.equal(start.showMotion,false);assert.equal(start.highlightStart,true);const operator=additionViewModel({view:ADDITION_VIEWS.operator,summand:-5,locked:false});assert.equal(operator.highlightOperator,true);assert.equal(operator.showMotion,false);});
test("nur freie stabile Zustände erlauben Summandenänderungen",()=>{const prompt=createAdditionState();assert.strictEqual(moveAdditionSummand(prompt,-2),prompt);const free={view:ADDITION_VIEWS.free,summand:-5,locked:false};assert.deepEqual(moveAdditionSummand(free,-2),{view:ADDITION_VIEWS.conclusion,summand:-2,locked:false});assert.equal(moveAdditionSummand(free,-99).summand,-6);assert.equal(moveAdditionSummand(free,99).summand,-1);});
test("Reset stellt aus jedem stabilen Zustand exakt die Irritation wieder her",()=>{for(const view of ["prompt","start","operator","summand","result","free","conclusion"])assert.deepEqual(resetAdditionState({view,summand:-1,locked:false}),createAdditionState());});

