import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
const files={home:await read("index.html"),homeCss:await read("home.css"),worker:await read("sw.js"),pages:await read("scripts/pages-runtime-files.mjs"),smoke:await read("scripts/smoke.mjs"),workflow:await read(".github/workflows/pages.yml")};
const packageJson=JSON.parse(await read("package.json"));
const runtimeFiles=["ungleichungen-negativ.html","negative-inequality.css","src/negative-inequality-app.js","src/negative-inequality-math.js","src/negative-inequality-state.js","src/negative-inequality-animation.js"];

test("Startseite integriert K4.3 genau einmal als dritte Kapitel-4-Karte",()=>{const chapter=files.home.match(/<section\s+id="gleichungen-ungleichungen"[\s\S]*?<\/section>/)?.[0];assert.ok(chapter);assert.equal((chapter.match(/class="module-card"/g)??[]).length,4);assert.equal((files.home.match(/href="\.\/ungleichungen-negativ\.html"/g)??[]).length,1);assert.match(chapter,/Warum dreht sich bei einer negativen Zahl das Ungleichheitszeichen um\?/);assert.match(chapter,/<span class="module-subtitle">Ungleichungen mit negativen Zahlen<\/span>/);assert.equal((files.home.match(/class="module-card"/g)??[]).length,25);});
test("Kapitel-4-Raster ordnet vier Karten responsiv ohne Überlauf",()=>{assert.match(files.homeCss,/\.chapter-equations \.module-grid\s*\{[^}]*repeat\(4,\s*minmax\(0,\s*1fr\)\)/s);assert.match(files.homeCss,/@media \(max-width: 720px\)[\s\S]*\.chapter-equations \.module-grid\s*\{[^}]*grid-template-columns:\s*1fr/s);assert.match(files.homeCss,/@media \(min-width: 721px\) and \(max-width: 1040px\)[\s\S]*\.chapter-equations \.module-grid\s*\{[^}]*repeat\(2,\s*minmax\(0,\s*1fr\)\)/s);});
test("Cache v30 enthält weiterhin die sechs K4.3-Laufzeitdateien",()=>{assert.match(files.worker,/mathe-unterrichts-app-v30/);assert.doesNotMatch(files.worker,/mathe-unterrichts-app-v25/);for(const file of runtimeFiles)assert.match(files.worker,new RegExp(file.replaceAll(".","\\.")));assert.doesNotMatch(files.worker,/render-negative-inequality-states|ungleichungen-negativ-(?:design|static\.test)/);});
test("Pages und Smoke enthalten jede neue Laufzeitdatei genau einmal",()=>{for(const file of runtimeFiles){assert.equal((files.pages.match(new RegExp(file.replaceAll(".","\\."),"g"))??[]).length,1);assert.equal((files.smoke.match(new RegExp(file.replaceAll(".","\\."),"g"))??[]).length,1);}});
test("Renderer ist im Paket und Pages-Workflow genau einmal verdrahtet",()=>{assert.equal(packageJson.scripts["test:negative-inequality-visual"],"node scripts/render-negative-inequality-states.mjs");assert.equal((files.workflow.match(/npm run test:negative-inequality-visual/g)??[]).length,1);});
