import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=path=>readFile(new URL(path,import.meta.url),"utf8");
const [html,css,app]=await Promise.all([read("../proportionale-zuordnungen.html").catch(()=>""),read("../proportional-comparison.css").catch(()=>""),read("../src/proportional-comparison-app.js").catch(()=>"")]);

test("Frage, Untertitel und Aha sind wortgetreu",()=>{assert.match(html,/Warum bedeutet „beide werden größer“ noch nicht proportional\?/);assert.match(html,/Proportionale Zuordnungen/);assert.match(html,/Gemeinsames Steigen allein reicht nicht\./);});
test("alle Prüfkriterien und der Schluss sind bis zu ihrem Gate echt hidden",()=>{for(const id of ["comparison-values","comparison-quotient","comparison-origin","comparison-scaling","comparison-explore","comparison-conclusion"])assert.match(html,new RegExp(`id="${id}"[^>]*hidden`));});
test("beide Graphen sind vollständig beschriftet und dynamisch benannt",()=>{assert.match(html,/Hefte<\/text>/);assert.match(html,/Preis in €<\/text>/);assert.match(html,/Kilometer<\/text>/);assert.equal((html.match(/class="y-scale"/g)??[]).length,2);assert.match(html,/class="y-scale"[^>]*>[\s\S]*?>12<\/text>/);assert.match(css,/\.y-scale text\s*{[^}]*text-anchor:\s*end/s);assert.match(app,/proportionalGraph\.setAttribute\("aria-label",model\.proportionalGraphLabel\)/);assert.match(app,/growingGraph\.setAttribute\("aria-label",model\.growingGraphLabel\)/);});
test("Controller synchronisiert Regler, Tabellen, Wertepaare und beide Graphpunkte",()=>{assert.match(app,/row\.classList\.toggle\("is-active",input===model\.activeRow\)/);assert.match(app,/proportionalPair\.textContent=model\.proportionalPair/);assert.match(app,/growingPair\.textContent=model\.growingPair/);assert.match(app,/proportionalPoint\.setAttribute\("cx",model\.proportionalPoint\.x\)/);assert.match(app,/growingPoint\.setAttribute\("cy",model\.growingPoint\.y\)/);assert.match(app,/comparisonInput\.addEventListener\("input"/);});
test("Animation, Reset, Datenschutz und responsive Regeln sind abgesichert",()=>{assert.match(app,/animationToken \+= 1/);assert.match(app,/prefers-reduced-motion: reduce/);assert.match(app,/token!==animationToken/);assert.match(html,/lokal · ohne Speicherung/);assert.match(html,/href="\.\/#zuordnungen"/);assert.doesNotMatch(html+css,/https?:\/\//);assert.match(css,/@media\(max-width:720px\)/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/\[hidden\]\{display:none!important\}/);});
