import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const root=new URL("../",import.meta.url),read=path=>readFile(new URL(path,root),"utf8");
const files={home:await read("index.html"),css:await read("home.css"),worker:await read("sw.js"),runtime:await read("scripts/pages-runtime-files.mjs"),smoke:await read("scripts/smoke.mjs"),workflow:await read(".github/workflows/pages.yml")};
const packageJson=JSON.parse(await read("package.json"));
const runtime=["proportionale-zuordnungen.html","proportional-comparison.css","src/proportional-comparison-app.js","src/proportional-comparison-animation.js","src/proportional-comparison-math.js","src/proportional-comparison-state.js"];

test("Startseite integriert K6.2 genau einmal als zweite Kapitel-6-Karte",()=>{const chapter=files.home.match(/<section id="zuordnungen"[\s\S]*?<\/section>/)?.[0];assert.ok(chapter);assert.equal((chapter.match(/class="module-card"/g)??[]).length,5);assert.equal((files.home.match(/href="\.\/proportionale-zuordnungen\.html"/g)??[]).length,1);assert.match(chapter,/Warum bedeutet „beide werden größer“ noch nicht proportional\?/);assert.match(chapter,/Proportionale Zuordnungen/);assert.equal((files.home.match(/class="module-card"/g)??[]).length,40);assert.match(files.css,/\.chapter-assignments \.module-grid\s*{[^}]*grid-template-columns:\s*repeat\(6, minmax\(0, 1fr\)\)/s);const mobile=files.css.match(/@media \(max-width: 720px\)[\s\S]*?(?=\n@media|$)/)?.[0];assert.match(mobile,/\.chapter-assignments \.module-grid\s*{[^}]*grid-template-columns:\s*1fr/s);const landscape=files.css.match(/@media \(orientation: landscape\) and \(min-width: 900px\) and \(max-width: 1500px\)[\s\S]*?(?=\n@media|$)/)?.[0];assert.match(landscape,/\.chapter-assignments \.module-card\s*{[^}]*grid-column:\s*span 2/s);});
test("Cache v45, Pages und Smoke enthalten die sechs K6.2-Laufzeitdateien",()=>{assert.match(files.worker,/mathe-unterrichts-app-v45/);assert.doesNotMatch(files.worker,/mathe-unterrichts-app-v32/);for(const file of runtime){const pattern=new RegExp(file.replaceAll(".","\\."));assert.match(files.worker,pattern);assert.match(files.runtime,pattern);assert.match(files.smoke,pattern);}});
test("Renderer ist im Paket und Workflow genau einmal verdrahtet",()=>{assert.equal(packageJson.scripts["test:proportional-comparison-visual"],"node scripts/render-proportional-comparison-states.mjs");assert.equal((files.workflow.match(/npm run test:proportional-comparison-visual/g)??[]).length,1);});
