import { spawn } from "node:child_process";
import { setTimeout as wait } from "node:timers/promises";

const port = 4183;
const server = spawn(process.execPath, ["scripts/serve.mjs"], {
  env: { ...process.env, PORT: String(port) },
  stdio: "ignore",
});

const expectedFiles = [
  "/",
  "/home.css",
  "/navigation.css",
  "/src/shell.js",
  "/winkelsumme.html",
  "/styles.css",
  "/src/app.js",
  "/src/geometry.js",
  "/dreiecksungleichung.html",
  "/triangle-inequality.css",
  "/src/triangle-inequality-app.js",
  "/src/triangle-inequality-geometry.js",
  "/dreiecksflaeche.html",
  "/triangle-area.css",
  "/src/triangle-area-app.js",
  "/src/triangle-area-animation.js",
  "/src/triangle-area-geometry.js",
  "/src/triangle-area-state.js",
  "/mittelsenkrechten.html",
  "/circumcircle.css",
  "/src/circumcircle-app.js",
  "/src/circumcircle-geometry.js",
  "/src/circumcircle-state.js",
  "/winkelhalbierende.html",
  "/incircle.css",
  "/src/incircle-app.js",
  "/src/incircle-geometry.js",
  "/src/incircle-state.js",
  "/eindeutige-dreiecke.html",
  "/unique-triangles.css",
  "/src/unique-triangles-app.js",
  "/src/unique-triangles-animation.js",
  "/src/unique-triangles-geometry.js",
  "/src/unique-triangles-state.js",
  "/zahlengerade.html",
  "/number-line.css",
  "/src/number-line-app.js",
  "/src/number-line-animation.js",
  "/src/number-line-geometry.js",
  "/src/number-line-state.js",
  "/ordnung.html",
  "/order-number-line.css",
  "/src/order-number-line-app.js",
  "/src/order-number-line-animation.js",
  "/src/order-number-line-geometry.js",
  "/src/order-number-line-state.js",
  "/betrag.html",
  "/absolute-value.css",
  "/src/absolute-value-app.js",
  "/src/absolute-value-animation.js",
  "/src/absolute-value-geometry.js",
  "/src/absolute-value-state.js",
  "/addition-negativ.html",
  "/addition-negative.css",
  "/src/addition-negative-app.js",
  "/src/addition-negative-animation.js",
  "/src/addition-negative-geometry.js",
  "/src/addition-negative-state.js",
  "/subtraktion-negativ.html",
  "/subtraction-negative.css",
  "/src/subtraction-negative-app.js",
  "/src/subtraction-negative-animation.js",
  "/src/subtraction-negative-geometry.js",
  "/src/subtraction-negative-state.js",
  "/multiplikation-negativ.html",
  "/multiplication-negative.css",
  "/src/multiplication-negative-app.js",
  "/src/multiplication-negative-animation.js",
  "/src/multiplication-negative-geometry.js",
  "/src/multiplication-negative-state.js",
  "/terme-variablen.html",
  "/terms-variables.css",
  "/src/terms-variables-app.js",
  "/src/terms-variables-math.js",
  "/src/terms-variables-state.js",
  "/gleichartige-terme.html",
  "/like-terms.css",
  "/src/like-terms-app.js",
  "/src/like-terms-math.js",
  "/src/like-terms-state.js",
  "/src/like-terms-animation.js",
  "/terme-multiplizieren.html",
  "/term-multiplication.css",
  "/src/term-multiplication-app.js",
  "/src/term-multiplication-math.js",
  "/src/term-multiplication-state.js",
  "/src/term-multiplication-animation.js",
  "/terme-dividieren.html",
  "/term-division.css",
  "/src/term-division-app.js",
  "/src/term-division-math.js",
  "/src/term-division-state.js",
  "/src/term-division-animation.js",
  "/plus-minus-klammern.html",
  "/bracket-sign.css",
  "/src/bracket-sign-app.js",
  "/src/bracket-sign-math.js",
  "/src/bracket-sign-state.js",
  "/src/bracket-sign-animation.js",
  "/ausmultiplizieren.html",
  "/distribution.css",
  "/src/distribution-app.js",
  "/src/distribution-math.js",
  "/src/distribution-state.js",
  "/src/distribution-animation.js",
  "/aequivalenzumformungen.html",
  "/equivalence.css",
  "/src/equivalence-app.js",
  "/src/equivalence-math.js",
  "/src/equivalence-state.js",
  "/src/equivalence-animation.js",
  "/terme-beide-seiten.html",
  "/both-sides.css",
  "/src/both-sides-app.js",
  "/src/both-sides-math.js",
  "/src/both-sides-state.js",
  "/src/both-sides-animation.js",
  "/sw.js",
  "/manifest.webmanifest",
  "/icon.svg",
];

try {
  await wait(250);
  for (const path of expectedFiles) {
    const response = await fetch(`http://127.0.0.1:${port}${path}`);
    if (!response.ok) {
      throw new Error(`${path} antwortete mit ${response.status}`);
    }
    if ((await response.arrayBuffer()).byteLength === 0) {
      throw new Error(`${path} ist leer`);
    }
  }
  console.log(`${expectedFiles.length}/${expectedFiles.length} lokale App-Ressourcen erreichbar`);
} finally {
  server.kill("SIGTERM");
}
